version: '2'
services:
  pact-broker:
    image: pactfoundation/pact-broker
    container_name: gatling-consumer-contract-pact-broker
    environment:
    - PACT_BROKER_DATABASE_ADAPTER=sqlite
    - PACT_BROKER_DATABASE_NAME=pact.sqlite
    - PACT_BROKER_BASIC_AUTH_USERNAME=pact-user
    - PACT_BROKER_BASIC_AUTH_PASSWORD=pact-password
    ports:
    - "9292:9292"